### ISSUE TITLE
State the license

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/logo#6]
We should state the license of our images.

**Comment by Newlifer** [comment]
CC?

**Comment by rexim** [comment]
> CC?

Which one?

**Comment by ForNeVeR** [comment]
CC-_what_? There's the whole bunch of various CC licenses.

**Comment by Newlifer** [comment]
Or... maybe public domain?

**Comment by ForNeVeR** [comment]
Nope, that creates some additional problems I'd like to avoid. I'd like to stick with CC-_something_, it seems to be okay.

**Comment by ForNeVeR** [comment]
Let's choose https://creativecommons.org/licenses/by/4.0/. Okay?

**Comment by Newlifer** [comment]
> Error 503 Backend fetch failed

**Comment by Minoru** [comment]
> > maybe public domain?
> 
> Nope, that creates some additional problems I'd like to avoid.

What problems? There's [CC0](https://creativecommons.org/choose/zero/) which is essentially "PD if applicable and as unrestricted as law permits otherwise".

CC BY 4.0 sounds fine for me, though, especially since our sole image creator (@rexim) agrees to use it.
